CREATE TABLE moalog.sync_entity_snapshots (
    id UUID PRIMARY KEY,
    household_id UUID NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id UUID NOT NULL,
    entity_version BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL,
    payload_json TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sync_snapshots_household FOREIGN KEY (household_id)
        REFERENCES moalog.households(id) ON DELETE CASCADE,
    CONSTRAINT uq_sync_snapshots_entity UNIQUE (household_id, entity_type, entity_id),
    CONSTRAINT ck_sync_snapshots_type CHECK (entity_type IN (
        'PLAN_CATALOG_ITEM', 'MONTHLY_PLAN_ITEM', 'EXPENSE_CATEGORY', 'EXPENSE_RECORD',
        'SALARY_INCOME', 'SALARY_ALLOCATION_CATEGORY', 'SALARY_ALLOCATION_DEDUCTION',
        'SALARY_ALLOCATION_CHILD', 'SALARY_ALLOCATION_GRANDCHILD', 'FIXED_COST_ITEM',
        'ASSET', 'ASSET_VALUATION', 'ASSET_GROWTH_RULE'
    )),
    CONSTRAINT ck_sync_snapshots_version CHECK (entity_version > 0),
    CONSTRAINT ck_sync_snapshots_payload CHECK (
        (deleted = TRUE AND payload_json IS NULL)
        OR (deleted = FALSE AND payload_json IS NOT NULL)
    )
);

CREATE INDEX ix_sync_snapshots_household ON moalog.sync_entity_snapshots(household_id);

CREATE TABLE moalog.sync_change_log (
    cursor BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id UUID NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id UUID NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_version BIGINT NOT NULL,
    payload_json TEXT,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sync_changes_household FOREIGN KEY (household_id)
        REFERENCES moalog.households(id) ON DELETE CASCADE,
    CONSTRAINT uq_sync_changes_household_cursor UNIQUE (household_id, cursor),
    CONSTRAINT ck_sync_changes_type CHECK (entity_type IN (
        'PLAN_CATALOG_ITEM', 'MONTHLY_PLAN_ITEM', 'EXPENSE_CATEGORY', 'EXPENSE_RECORD',
        'SALARY_INCOME', 'SALARY_ALLOCATION_CATEGORY', 'SALARY_ALLOCATION_DEDUCTION',
        'SALARY_ALLOCATION_CHILD', 'SALARY_ALLOCATION_GRANDCHILD', 'FIXED_COST_ITEM',
        'ASSET', 'ASSET_VALUATION', 'ASSET_GROWTH_RULE'
    )),
    CONSTRAINT ck_sync_changes_operation CHECK (operation IN ('UPSERT', 'DELETE')),
    CONSTRAINT ck_sync_changes_version CHECK (entity_version > 0),
    CONSTRAINT ck_sync_changes_payload CHECK (
        (operation = 'DELETE' AND payload_json IS NULL)
        OR (operation = 'UPSERT' AND payload_json IS NOT NULL)
    )
);

CREATE INDEX ix_sync_changes_household_cursor ON moalog.sync_change_log(household_id, cursor);

CREATE TABLE moalog.sync_processed_mutations (
    id UUID PRIMARY KEY,
    household_id UUID NOT NULL,
    mutation_id UUID NOT NULL,
    device_id UUID NOT NULL,
    content_fingerprint VARCHAR(64) NOT NULL,
    entity_type VARCHAR(50) NOT NULL,
    entity_id UUID NOT NULL,
    applied_version BIGINT NOT NULL,
    change_cursor BIGINT NOT NULL,
    processed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sync_processed_household FOREIGN KEY (household_id)
        REFERENCES moalog.households(id) ON DELETE CASCADE,
    CONSTRAINT fk_sync_processed_change FOREIGN KEY (household_id, change_cursor)
        REFERENCES moalog.sync_change_log(household_id, cursor) ON DELETE CASCADE,
    CONSTRAINT uq_sync_processed_mutation UNIQUE (household_id, mutation_id),
    CONSTRAINT ck_sync_processed_fingerprint CHECK (LENGTH(content_fingerprint) = 64),
    CONSTRAINT ck_sync_processed_version CHECK (applied_version > 0)
);

CREATE INDEX ix_sync_processed_household ON moalog.sync_processed_mutations(household_id);
CREATE INDEX ix_sync_processed_device ON moalog.sync_processed_mutations(household_id, device_id);
