ALTER TABLE moalog.sync_entity_snapshots DROP CONSTRAINT ck_sync_snapshots_type;
ALTER TABLE moalog.sync_entity_snapshots ADD CONSTRAINT ck_sync_snapshots_type CHECK (entity_type IN (
    'PLAN_CATALOG_ITEM', 'MONTHLY_PLAN_ITEM', 'EXPENSE_CATEGORY', 'EXPENSE_RECORD',
    'SALARY_INCOME', 'SALARY_ALLOCATION_CATEGORY', 'SALARY_ALLOCATION_DEDUCTION',
    'SALARY_ALLOCATION_CHILD', 'SALARY_ALLOCATION_GRANDCHILD', 'FIXED_COST_ITEM',
    'ASSET', 'ASSET_VALUATION', 'ASSET_GROWTH_RULE', 'MAINTENANCE_FEE_MONTH'
));

ALTER TABLE moalog.sync_change_log DROP CONSTRAINT ck_sync_changes_type;
ALTER TABLE moalog.sync_change_log ADD CONSTRAINT ck_sync_changes_type CHECK (entity_type IN (
    'PLAN_CATALOG_ITEM', 'MONTHLY_PLAN_ITEM', 'EXPENSE_CATEGORY', 'EXPENSE_RECORD',
    'SALARY_INCOME', 'SALARY_ALLOCATION_CATEGORY', 'SALARY_ALLOCATION_DEDUCTION',
    'SALARY_ALLOCATION_CHILD', 'SALARY_ALLOCATION_GRANDCHILD', 'FIXED_COST_ITEM',
    'ASSET', 'ASSET_VALUATION', 'ASSET_GROWTH_RULE', 'MAINTENANCE_FEE_MONTH'
));
