spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/moalog}
    username: ${SPRING_DATASOURCE_USERNAME:moalog}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD}}
