package kr.jm.moalog.feature.plan.presentation

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.semantics.LiveRegionMode
import androidx.compose.ui.semantics.Role
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.liveRegion
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import kr.jm.moalog.core.designsystem.MoaLogColors
import kr.jm.moalog.core.model.*
import org.koin.compose.koinInject
import org.koin.core.parameter.parametersOf

@Composable fun SalaryAllocationDetailRoute(args:SalaryAllocationDetailArgs,onBack:()->Unit,onEditCategory:(Long)->Unit,stateHolder:SalaryAllocationDetailStateHolder=koinInject(parameters={parametersOf(args)})) { val state by stateHolder.state.collectAsStateWithLifecycle();DisposableEffect(stateHolder){stateHolder.start();onDispose{stateHolder.close()}};SalaryAllocationDetailScreen(state,stateHolder::onAction,onBack,onEditCategory) }

@Composable fun SalaryAllocationDetailScreen(state:SalaryAllocationDetailUiState,onAction:(SalaryAllocationDetailAction)->Unit,onBack:()->Unit,onEditCategory:(Long)->Unit,modifier:Modifier=Modifier){val category=state.category;LazyColumn(modifier.fillMaxSize().background(MoaLogColors.Canvas),contentPadding=PaddingValues(start=20.dp,end=20.dp,top=4.dp,bottom=32.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Row(Modifier.fillMaxWidth().heightIn(min=48.dp),verticalAlignment=Alignment.CenterVertically){IconButton(onBack){Icon(Icons.AutoMirrored.Filled.ArrowBack,"뒤로")};Text(category?.let{"${it.name} 배분 상세"}?:"배분 상세",Modifier.weight(1f),style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);category?.let{TextButton({onEditCategory(it.id)},Modifier.heightIn(min=48.dp)){Text("편집")}}}};if(state.isLoading)item{Box(Modifier.fillMaxWidth().padding(40.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}}else if(category==null)item{Text("배분 항목을 찾을 수 없어요",color=MaterialTheme.colorScheme.error)}else{item{DetailHero(state)};item{Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text("배분 항목",style=MaterialTheme.typography.titleMedium,fontWeight=FontWeight.Bold);Text("중분류 ${category.children.size}개 · 펼쳐서 소분류 관리",color=MoaLogColors.MutedInk,style=MaterialTheme.typography.labelSmall)}}};if(category.children.isEmpty())item{Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(14.dp),color=Color.White,border=BorderStroke(1.dp,MoaLogColors.CardBorder)){Text("아직 중분류 항목이 없어요",Modifier.fillMaxWidth().padding(28.dp),textAlign=TextAlign.Center,color=MoaLogColors.MutedInk)}}else items(category.children,key={it.id}){child->ChildGroup(child,child.id in state.expandedChildIds,onAction)};item{OutlinedButton({onAction(SalaryAllocationDetailAction.OpenChildEditor())},Modifier.fillMaxWidth().heightIn(min=52.dp),shape=RoundedCornerShape(12.dp)){Icon(Icons.Default.AddCircle,null);Text("중분류 추가",Modifier.padding(start=8.dp))}}};state.error?.let{item{Text(it,Modifier.semantics{liveRegion=LiveRegionMode.Assertive},color=MaterialTheme.colorScheme.error)}}};state.draft?.let{ChildEditorDialog(it,state.error,state.isSaving,onAction)};state.grandchildDraft?.let{GrandchildEditorDialog(it,state.error,state.isSaving,onAction)}}

@Composable private fun DetailHero(state: SalaryAllocationDetailUiState){val category=state.category?:return;val target=state.targetAmountWon;val total=state.childTotalWon;val diff=if(target!=null&&total!=null)target-total else null;Surface(color=Color.White,shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,MoaLogColors.CardBorder)){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,color=Color(0xFFE7F0ED)){Icon(Icons.Default.TrendingUp,null,Modifier.padding(10.dp),tint=MoaLogColors.DeepTeal)};Column(Modifier.padding(start=10.dp)){Text(category.name,fontWeight=FontWeight.Bold);Text("${category.attributionMonth.year}년 ${category.attributionMonth.month}월 배분",color=MoaLogColors.MutedInk,style=MaterialTheme.typography.labelSmall)}};Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(12.dp)){HeroMetric("목표 배분액",target?.let(::detailWon)?:"계산 불가",Modifier.weight(1f));HeroMetric("세부 합계",if(state.hasChildTotalOverflow)"합계 범위 초과" else total?.let(::detailWon)?:"미입력",Modifier.weight(1f))};LinearProgressIndicator(progress={if(target!=null&&target>0&&total!=null)(total.toDouble()/target.toDouble()).toFloat().coerceIn(0f,1f) else 0f},Modifier.fillMaxWidth().semantics{contentDescription="목표 배분액과 세부 합계 진행률"},color=MoaLogColors.DeepTeal,trackColor=Color(0xFFE0E3DF));if(diff!=null&&diff!=0L)Row(Modifier.fillMaxWidth().background(Color(0xFFFDECEE),RoundedCornerShape(10.dp)).padding(10.dp)){Icon(Icons.Default.Warning,null,tint=MoaLogColors.Overspend);Text("차액 ${detailWon(kotlin.math.abs(diff))} ${if(diff>0)"미배분" else "초과"}",Modifier.padding(start=8.dp),color=MoaLogColors.Overspend,fontWeight=FontWeight.SemiBold)}}}}
@Composable private fun HeroMetric(label:String,value:String,modifier:Modifier=Modifier){Column(modifier){Text(label,color=MoaLogColors.MutedInk,style=MaterialTheme.typography.labelSmall);Text(value,style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold,color=MoaLogColors.TealInk)}}
@Composable private fun ChildGroup(child:SalaryAllocationChild,expanded:Boolean,onAction:(SalaryAllocationDetailAction)->Unit){val subtotal=child.subtotal();val subtotalOverflow=child.hasSubtotalOverflow();Surface(Modifier.fillMaxWidth(),color=Color.White,shape=RoundedCornerShape(12.dp),border=BorderStroke(1.dp,MoaLogColors.CardBorder)){Column{Row(Modifier.fillMaxWidth().heightIn(min=72.dp).clickable(role=Role.Button,onClickLabel="${child.name} ${if(expanded)"접기" else "펼치기"}"){onAction(SalaryAllocationDetailAction.ToggleChild(child.id))}.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Surface(shape=CircleShape,color=Color(0xFFE7F0ED)){Icon(Icons.Default.Savings,null,Modifier.padding(8.dp).size(19.dp),tint=MoaLogColors.DeepTeal)};Column(Modifier.padding(start=10.dp).weight(1f)){Text(child.name,fontWeight=FontWeight.SemiBold);Text(if(child.grandchildren.isEmpty())"소분류 없음" else "소분류 ${child.grandchildren.size}개",color=MoaLogColors.MutedInk,style=MaterialTheme.typography.labelSmall)};Text(if(subtotalOverflow)"합계 범위 초과" else subtotal?.let(::detailWon)?:"미입력",color=if(subtotal==null)MoaLogColors.Overspend else MoaLogColors.TealInk,fontWeight=FontWeight.Bold);IconButton({onAction(SalaryAllocationDetailAction.OpenChildEditor(child))},Modifier.size(48.dp)){Icon(Icons.Default.Edit,"${child.name} 중분류 편집")};Icon(if(expanded)Icons.Default.ExpandLess else Icons.Default.ExpandMore,null)};if(expanded){child.grandchildren.forEach{item->Row(Modifier.fillMaxWidth().heightIn(min=56.dp).clickable(role=Role.Button,onClickLabel="${item.name} 소분류 편집"){onAction(SalaryAllocationDetailAction.OpenGrandchildEditor(child.id,item))}.padding(start=28.dp,end=12.dp),verticalAlignment=Alignment.CenterVertically){Text(item.name,Modifier.weight(1f));Text(item.amountWon?.let(::detailWon)?:"미입력",color=MoaLogColors.TealInk);Icon(Icons.Default.ChevronRight,null)}};TextButton({onAction(SalaryAllocationDetailAction.OpenGrandchildEditor(child.id))},Modifier.fillMaxWidth().heightIn(min=48.dp)){Icon(Icons.Default.Add,null);Text("소분류 추가")}}}}}
@Composable private fun ChildEditorDialog(d:SalaryChildDraft,error:String?,saving:Boolean,onAction:(SalaryAllocationDetailAction)->Unit){Dialog(onDismissRequest={onAction(SalaryAllocationDetailAction.CloseEditor)}){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),color=MoaLogColors.Canvas){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(if(d.id==0L)"하위 항목 추가" else "하위 항목 편집",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);IconButton({onAction(SalaryAllocationDetailAction.CloseEditor)}){Icon(Icons.Default.Close,"닫기")}};DetailField("이름",d.name,{onAction(SalaryAllocationDetailAction.ChangeName(it))},"예: 카카오뱅크 적금");DetailField("거래처 / 상세 메모",d.memo,{onAction(SalaryAllocationDetailAction.ChangeMemo(it))},"선택 입력");if(d.usesGrandchildSubtotal){Surface(color=Color(0xFFE7F0ED),shape=RoundedCornerShape(10.dp)){Text("월 배분 금액은 소분류 금액의 합계로 계산됩니다.",Modifier.fillMaxWidth().padding(12.dp),color=MoaLogColors.DeepTeal,style=MaterialTheme.typography.bodySmall)}}else Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text("월 배분 금액",style=MaterialTheme.typography.labelMedium,fontWeight=FontWeight.SemiBold);OutlinedTextField(d.amount,{onAction(SalaryAllocationDetailAction.ChangeAmount(it))},Modifier.fillMaxWidth().heightIn(min=52.dp).semantics{contentDescription="월 배분 금액"},suffix={Text("원")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number),singleLine=true,shape=RoundedCornerShape(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf(50_000L,100_000L).forEach{inc->AssistChip({onAction(SalaryAllocationDetailAction.ChangeAmount(addWonInput(d.amount,inc)))},{Text("+${inc/10_000}만")},Modifier.heightIn(min=48.dp))}}};error?.let{Text(it,Modifier.semantics{liveRegion=LiveRegionMode.Assertive},color=MaterialTheme.colorScheme.error)};if(d.id!=0L)TextButton({onAction(SalaryAllocationDetailAction.Delete)},Modifier.fillMaxWidth().heightIn(min=48.dp),colors=ButtonDefaults.textButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("항목 삭제")};Button({onAction(SalaryAllocationDetailAction.Save)},Modifier.fillMaxWidth().heightIn(min=52.dp),enabled=!saving){Text("저장하기")}}}}}
@Composable private fun GrandchildEditorDialog(d:SalaryGrandchildDraft,error:String?,saving:Boolean,onAction:(SalaryAllocationDetailAction)->Unit){Dialog(onDismissRequest={onAction(SalaryAllocationDetailAction.CloseGrandchildEditor)}){Surface(Modifier.fillMaxWidth(),shape=RoundedCornerShape(20.dp),color=MoaLogColors.Canvas){Column(Modifier.padding(20.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text(if(d.id==0L)"소분류 추가" else "소분류 편집",Modifier.weight(1f),style=MaterialTheme.typography.titleLarge,fontWeight=FontWeight.Bold);IconButton({onAction(SalaryAllocationDetailAction.CloseGrandchildEditor)}){Icon(Icons.Default.Close,"닫기")}};DetailField("이름",d.name,{onAction(SalaryAllocationDetailAction.ChangeGrandchildName(it))},"예: 수아 ISA");DetailField("메모",d.memo,{onAction(SalaryAllocationDetailAction.ChangeGrandchildMemo(it))},"선택 입력");OutlinedTextField(d.amount,{onAction(SalaryAllocationDetailAction.ChangeGrandchildAmount(it))},Modifier.fillMaxWidth().heightIn(min=52.dp).semantics{contentDescription="소분류 월 배분 금액"},label={Text("월 배분 금액")},suffix={Text("원")},keyboardOptions=KeyboardOptions(keyboardType=KeyboardType.Number),singleLine=true);error?.let{Text(it,color=MaterialTheme.colorScheme.error)};if(d.id!=0L)TextButton({onAction(SalaryAllocationDetailAction.DeleteGrandchild)},Modifier.fillMaxWidth().heightIn(min=48.dp),colors=ButtonDefaults.textButtonColors(contentColor=MaterialTheme.colorScheme.error)){Text("소분류 삭제")};Button({onAction(SalaryAllocationDetailAction.SaveGrandchild)},Modifier.fillMaxWidth().heightIn(min=52.dp),enabled=!saving){Text("저장하기")}}}}}
@Composable private fun DetailField(label:String,value:String,onChange:(String)->Unit,placeholder:String){Column(verticalArrangement=Arrangement.spacedBy(6.dp)){Text(label,style=MaterialTheme.typography.labelMedium,fontWeight=FontWeight.SemiBold);OutlinedTextField(value,onChange,Modifier.fillMaxWidth().heightIn(min=52.dp),placeholder={Text(placeholder)},singleLine=true,shape=RoundedCornerShape(10.dp))}}
private fun detailWon(value:Long)=value.toString().reversed().chunked(3).joinToString(",").reversed()+"원"
private fun addWonInput(value: String, increment: Long): String {
    val current = value.toLongOrNull() ?: 0L
    return if (Long.MAX_VALUE - current < increment) value else (current + increment).toString()
}
